version: 2

build:
    os: ubuntu-22.04

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt